apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: bgppeers.crd.projectcalico.org
spec:
  group: crd.projectcalico.org
  names:
    kind: BGPPeer
    listKind: BGPPeerList
    plural: bgppeers
    singular: bgppeer
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                asNumber:
                  format: int32
                  type: integer
                filters:
                  items:
                    type: string
                  type: array
                keepOriginalNextHop:
                  type: boolean
                keepaliveTime:
                  type: string
                localASNumber:
                  format: int32
                  type: integer
                localWorkloadSelector:
                  type: string
                maxRestartTime:
                  type: string
                nextHopMode:
                  enum:
                    - Auto
                    - Self
                    - Keep
                  type: string
                node:
                  type: string
                nodeSelector:
                  type: string
                numAllowedLocalASNumbers:
                  format: int32
                  type: integer
                password:
                  properties:
                    secretKeyRef:
                      properties:
                        key:
                          type: string
                        name:
                          default: ""
                          type: string
                        optional:
                          type: boolean
                      required:
                        - key
                      type: object
                      x-kubernetes-map-type: atomic
                  type: object
                peerIP:
                  type: string
                peerSelector:
                  type: string
                reachableBy:
                  type: string
                reversePeering:
                  allOf:
                    - enum:
                        - Auto
                        - Manual
                    - enum:
                        - Auto
                        - Manual
                  type: string
                sourceAddress:
                  enum:
                    - UseNodeIP
                    - None
                  type: string
                ttlSecurity:
                  type: integer
              type: object
              x-kubernetes-validations:
                - message: node and nodeSelector cannot both be set
                  rule:
                    (!has(self.node) || size(self.node) == 0) || (!has(self.nodeSelector)
                    || size(self.nodeSelector) == 0)
                - message: peerIP and peerSelector cannot both be set
                  rule:
                    (!has(self.peerIP) || size(self.peerIP) == 0) || (!has(self.peerSelector)
                    || size(self.peerSelector) == 0)
                - message: asNumber must be empty when peerSelector is set
                  rule:
                    (!has(self.peerSelector) || size(self.peerSelector) == 0) || !has(self.asNumber)
                    || self.asNumber == 0
                - message: peerIP must be empty when localWorkloadSelector is set
                  rule:
                    (!has(self.localWorkloadSelector) || size(self.localWorkloadSelector)
                    == 0) || (!has(self.peerIP) || size(self.peerIP) == 0)
                - message: peerSelector must be empty when localWorkloadSelector is set
                  rule:
                    (!has(self.localWorkloadSelector) || size(self.localWorkloadSelector)
                    == 0) || (!has(self.peerSelector) || size(self.peerSelector) == 0)
                - message: asNumber is required when localWorkloadSelector is set
                  rule:
                    (!has(self.localWorkloadSelector) || size(self.localWorkloadSelector)
                    == 0) || (has(self.asNumber) && self.asNumber != 0)
          type: object
      served: true
      storage: true
