# This file contains only the changes from the defaults
# https://jekyllrb.com/docs/configuration/#default-configuration

# Make our URLs look nice. We're not a blog with dated posts, we just want the title.
permalink:     /:title.html

archive: false
noindex: false
version_pattern: v?([0-9]+\.[0-9]+)(?:.*?)$

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

url: https://projectcalico.docs.tigera.io

repository: projectcalico/calico

prodname: Calico
prodnamedash: calico
prodnameWindows: Calico for Windows
rootDirWindows: C:\CalicoWindows
nodecontainer: calico/node
noderunning: calico-node

open_source: true

# DEPRECATED: use imageNames stored in per-directory defaults, e.g. 'page.imageNames'
imageNames:
  node: docker.io/calico/node
  calicoctl: docker.io/calico/ctl
  apiserver: docker.io/calico/apiserver
  typha: docker.io/calico/typha
  cni: docker.io/calico/cni
  kubeControllers: docker.io/calico/kube-controllers
  calico-upgrade: docker.io/calico/upgrade
  calico/windows: docker.io/calico/windows
  flannel: quay.io/coreos/flannel
  flannelMigration: docker.io/calico/flannel-migration-controller
  dikastes: docker.io/calico/dikastes
  pilot-webhook: docker.io/calico/pilot-webhook
  flexvol: docker.io/calico/pod2daemon-flexvol
  csi-driver: docker.io/calico/csi

# List of files to exclude. These files won't get included in the deployed site.
exclude:
  - release-scripts
  - LICENSE
  - Makefile
  - README.md
  - RELEASING.md
  - DEVELOPER_GUIDE.md
  - CONTRIBUTING_DOCS.md
  - CONTRIBUTING_CODE.md
  - DOC_STYLE_GUIDE.md
  - hack
  - vendor

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Set to 'true' to show warning that points users to latest version of each page.
is_latest: false

defaults:
  -
    scope:
      path: ""
    values:
      version: v3.23
      layout: docwithnav
      show_title: true
      show_read_time: true
      show_toc: true
      vppbranch: v3.23.0  # The branch in vpp repo that these docs should point to for manifests, etc
      sitemap: true
      registry:
      # A lookup map for imageNames based on component names.
      # Keys should be camel-cased *and* match the keys used in versions.yml components.
      imageNames:
        calico/node: calico/node
        calicoctl: calico/ctl
        typha: calico/typha
        calico/cni: calico/cni
        calico/apiserver: calico/apiserver
        calico/kube-controllers: calico/kube-controllers
        calico-upgrade: calico-upgrade
        calico/windows: calico/windows
        flannel: quay.io/coreos/flannel
        flannelMigration: calico/flannel-migration-controller
        calico/dikastes: calico/dikastes
        pilot-webhook: calico/pilot-webhook
        flexvol: calico/pod2daemon-flexvol
        csi-driver: calico/csi
