version: 2
updates:
  - package-ecosystem: "gomod"
    target-branch: "release-v3.31"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "docs-not-required"
      - "release-note-not-required"
      - "dependencies"
