apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: bgpfilters.projectcalico.org
spec:
  group: projectcalico.org
  names:
    kind: BGPFilter
    listKind: BGPFilterList
    plural: bgpfilters
    singular: bgpfilter
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - name: v3
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                exportV4:
                  items:
                    properties:
                      action:
                        enum:
                          - Accept
                          - Reject
                        type: string
                      cidr:
                        format: cidr
                        type: string
                      interface:
                        type: string
                      matchOperator:
                        enum:
                          - Equal
                          - NotEqual
                          - In
                          - NotIn
                        type: string
                      prefixLength:
                        properties:
                          max:
                            format: int32
                            maximum: 32
                            minimum: 0
                            type: integer
                          min:
                            format: int32
                            maximum: 32
                            minimum: 0
                            type: integer
                        type: object
                        x-kubernetes-map-type: atomic
                      source:
                        enum:
                          - RemotePeers
                        type: string
                    required:
                      - action
                    type: object
                    x-kubernetes-map-type: atomic
                    x-kubernetes-validations:
                      - message: cidr and matchOperator must both be set or both be empty
                        rule:
                          (has(self.cidr) && size(self.cidr) > 0) == (has(self.matchOperator)
                          && size(self.matchOperator) > 0)
                      - message: cidr is required when prefixLength is set
                        rule:
                          "!has(self.prefixLength) || (has(self.cidr) && size(self.cidr)
                          > 0)"
                  type: array
                exportV6:
                  items:
                    properties:
                      action:
                        enum:
                          - Accept
                          - Reject
                        type: string
                      cidr:
                        format: cidr
                        type: string
                      interface:
                        type: string
                      matchOperator:
                        enum:
                          - Equal
                          - NotEqual
                          - In
                          - NotIn
                        type: string
                      prefixLength:
                        properties:
                          max:
                            format: int32
                            maximum: 128
                            minimum: 0
                            type: integer
                          min:
                            format: int32
                            maximum: 128
                            minimum: 0
                            type: integer
                        type: object
                        x-kubernetes-map-type: atomic
                      source:
                        enum:
                          - RemotePeers
                        type: string
                    required:
                      - action
                    type: object
                    x-kubernetes-map-type: atomic
                    x-kubernetes-validations:
                      - message: cidr and matchOperator must both be set or both be empty
                        rule:
                          (has(self.cidr) && size(self.cidr) > 0) == (has(self.matchOperator)
                          && size(self.matchOperator) > 0)
                      - message: cidr is required when prefixLength is set
                        rule:
                          "!has(self.prefixLength) || (has(self.cidr) && size(self.cidr)
                          > 0)"
                  type: array
                importV4:
                  items:
                    properties:
                      action:
                        enum:
                          - Accept
                          - Reject
                        type: string
                      cidr:
                        format: cidr
                        type: string
                      interface:
                        type: string
                      matchOperator:
                        enum:
                          - Equal
                          - NotEqual
                          - In
                          - NotIn
                        type: string
                      prefixLength:
                        properties:
                          max:
                            format: int32
                            maximum: 32
                            minimum: 0
                            type: integer
                          min:
                            format: int32
                            maximum: 32
                            minimum: 0
                            type: integer
                        type: object
                        x-kubernetes-map-type: atomic
                      source:
                        enum:
                          - RemotePeers
                        type: string
                    required:
                      - action
                    type: object
                    x-kubernetes-map-type: atomic
                    x-kubernetes-validations:
                      - message: cidr and matchOperator must both be set or both be empty
                        rule:
                          (has(self.cidr) && size(self.cidr) > 0) == (has(self.matchOperator)
                          && size(self.matchOperator) > 0)
                      - message: cidr is required when prefixLength is set
                        rule:
                          "!has(self.prefixLength) || (has(self.cidr) && size(self.cidr)
                          > 0)"
                  type: array
                importV6:
                  items:
                    properties:
                      action:
                        enum:
                          - Accept
                          - Reject
                        type: string
                      cidr:
                        format: cidr
                        type: string
                      interface:
                        type: string
                      matchOperator:
                        enum:
                          - Equal
                          - NotEqual
                          - In
                          - NotIn
                        type: string
                      prefixLength:
                        properties:
                          max:
                            format: int32
                            maximum: 128
                            minimum: 0
                            type: integer
                          min:
                            format: int32
                            maximum: 128
                            minimum: 0
                            type: integer
                        type: object
                        x-kubernetes-map-type: atomic
                      source:
                        enum:
                          - RemotePeers
                        type: string
                    required:
                      - action
                    type: object
                    x-kubernetes-map-type: atomic
                    x-kubernetes-validations:
                      - message: cidr and matchOperator must both be set or both be empty
                        rule:
                          (has(self.cidr) && size(self.cidr) > 0) == (has(self.matchOperator)
                          && size(self.matchOperator) > 0)
                      - message: cidr is required when prefixLength is set
                        rule:
                          "!has(self.prefixLength) || (has(self.cidr) && size(self.cidr)
                          > 0)"
                  type: array
              type: object
          required:
            - metadata
            - spec
          type: object
      served: true
      storage: true
