apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: clusterinformations.projectcalico.org
spec:
  group: projectcalico.org
  names:
    kind: ClusterInformation
    listKind: ClusterInformationList
    plural: clusterinformations
    shortNames:
      - clusterinfo
      - clusterinfos
    singular: clusterinformation
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - name: v3
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                calicoVersion:
                  type: string
                clusterGUID:
                  type: string
                clusterType:
                  type: string
                datastoreReady:
                  type: boolean
                variant:
                  type: string
              type: object
          required:
            - metadata
            - spec
          type: object
      served: true
      storage: true
