apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: bgppeers.projectcalico.org
spec:
  group: projectcalico.org
  names:
    kind: BGPPeer
    listKind: BGPPeerList
    plural: bgppeers
    singular: bgppeer
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - description: Selector for the nodes that should have this peering
          jsonPath: .spec.nodeSelector
          name: Node Selector
          type: string
        - description:
            The node name identifying the Calico node instance that is targeted
            by this peer
          jsonPath: .spec.node
          name: Node
          type: string
        - description:
            The optional Local AS Number to use when peering with this remote
            peer
          jsonPath: .spec.localASNumber
          name: Local ASN
          type: string
        - description: Selector for the remote nodes to peer with
          jsonPath: .spec.peerSelector
          name: Peer Selector
          type: string
        - description:
            The IP address of the peer followed by an optional port number
            to peer with
          jsonPath: .spec.peerIP
          name: Peer IP
          type: string
        - description: The AS Number of the peer
          jsonPath: .spec.asNumber
          name: Peer ASN
          type: string
      name: v3
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                asNumber:
                  format: int32
                  type: integer
                filters:
                  items:
                    type: string
                  type: array
                keepOriginalNextHop:
                  type: boolean
                keepaliveTime:
                  type: string
                localASNumber:
                  format: int32
                  type: integer
                localWorkloadSelector:
                  type: string
                maxRestartTime:
                  type: string
                nextHopMode:
                  enum:
                    - Auto
                    - Self
                    - Keep
                  type: string
                node:
                  type: string
                nodeSelector:
                  type: string
                numAllowedLocalASNumbers:
                  format: int32
                  type: integer
                password:
                  properties:
                    secretKeyRef:
                      properties:
                        key:
                          type: string
                        name:
                          default: ""
                          type: string
                        optional:
                          type: boolean
                      required:
                        - key
                      type: object
                      x-kubernetes-map-type: atomic
                  type: object
                peerIP:
                  type: string
                peerSelector:
                  type: string
                reachableBy:
                  type: string
                reversePeering:
                  allOf:
                    - enum:
                        - Auto
                        - Manual
                    - enum:
                        - Auto
                        - Manual
                  type: string
                sourceAddress:
                  enum:
                    - UseNodeIP
                    - None
                  type: string
                ttlSecurity:
                  type: integer
              type: object
          required:
            - metadata
            - spec
          type: object
      served: true
      storage: true
      subresources: {}
