apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: hostendpoints.projectcalico.org
spec:
  group: projectcalico.org
  names:
    kind: HostEndpoint
    listKind: HostEndpointList
    plural: hostendpoints
    shortNames:
      - hep
      - heps
    singular: hostendpoint
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - description:
            The node name identifying the Calico node instance that is targeted
            by this HostEndpoint
          jsonPath: .spec.node
          name: Node
          type: string
        - description: The name of the interface that is targeted by this HostEndpoint
          jsonPath: .spec.interfaceName
          name: Interface
          type: string
      name: v3
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                expectedIPs:
                  items:
                    type: string
                  type: array
                  x-kubernetes-list-type: set
                interfaceName:
                  type: string
                node:
                  type: string
                ports:
                  items:
                    properties:
                      name:
                        type: string
                      port:
                        maximum: 65535
                        minimum: 1
                        type: integer
                      protocol:
                        anyOf:
                          - type: integer
                          - type: string
                        pattern: ^.*
                        x-kubernetes-int-or-string: true
                    required:
                      - name
                      - port
                      - protocol
                    type: object
                  type: array
                profiles:
                  items:
                    type: string
                  type: array
                  x-kubernetes-list-type: set
              type: object
              x-kubernetes-validations:
                - message: at least one of interfaceName or expectedIPs must be specified
                  rule:
                    (has(self.interfaceName) && size(self.interfaceName) > 0) || (has(self.expectedIPs)
                    && size(self.expectedIPs) > 0)
                - message: node must be specified
                  rule: has(self.node) && size(self.node) > 0
          required:
            - metadata
            - spec
          type: object
      served: true
      storage: true
      subresources: {}
