---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.3
  name: ipamconfigurations.projectcalico.org
spec:
  group: projectcalico.org
  names:
    kind: IPAMConfiguration
    listKind: IPAMConfigurationList
    plural: ipamconfigurations
    singular: ipamconfiguration
  preserveUnknownFields: false
  scope: Cluster
  versions:
  - name: v3
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              maxBlocksPerHost:
                format: int32
                type: integer
              strictAffinity:
                type: boolean
            required:
            - strictAffinity
            type: object
        type: object
    served: true
    storage: true
