bigheader: "Security"
path: /security/
order: 3
section:
- title: Adopt a zero trust network model for security
  path: /security/adopt-zero-trust
- title: Get started with Kubernetes network policy
  path: /security/kubernetes-network-policy
- title: Get started with Calico network policy
  path: /security/calico-network-policy
- title: Enforce network policy using Istio
  path: /security/enforce-policy-istio
- title: Enable default deny for Kubernetes pods
  path: /security/kubernetes-default-deny
- title: Use namespace in policy rules
  path: /security/namespace-policy
- title: Use service accounts in policy rules
  path: /security/service-accounts
- title: Use HTTP methods and paths in policy rules
  path: /security/http-methods
- title: Use ICMP/ping in policy rules
  path: /security/icmp-ping
- title: Use external IPs or networks in policy rules
  path: /security/external-ips-policy
- title: Protect hosts
  path: /security/protect-hosts
- title: Apply policy to Kubernetes node ports
  path: /security/kubernetes-node-ports
- title: Apply policy to services exposed externally as cluster IPs
  path: /security/services-cluster-ips
- title: Apply policy to host forwarded traffic
  path: /security/host-forwarded-traffic
- title: Enable extreme high-connection workloads
  path: /security/high-connection-workloads
- title: Defend against DoS attacks
  path: /security/defend-dos-attack
- title: Get started with Calico network policy for OpenStack
  path: /security/network-policy-openstack
- title: Secure Calico component communications
  path: /security/comms/
  section:
  - title: Configure encryption and authentication
    path: /security/comms/crypto-auth
  - title: Schedule to well-known nodes
    path: /security/comms/reduce-nodes
  - title: Secure Calico Prometheus endpoints
    path: /security/comms/secure-metrics
- title: Tutorials
  path: /security/tutorials/
  section:
  - title: Enforce network policy using Istio tutorial
    path: /security/tutorials/app-layer-policy/enforce-policy-istio
  - title: Protect host tutorial
    path: /security/tutorials/protect-hosts
  - title: Kubernetes policy, demo
    path: /security/tutorials/kubernetes-policy-demo/kubernetes-demo
  - title: Kubernetes policy, basic tutorial
    path: /security/tutorials/kubernetes-policy-basic
  - title: Kubernetes policy, advanced tutorial
    path: /security/tutorials/kubernetes-policy-advanced
